### ISSUE TITLE
CodeShell-Chat输出不会正常结束

### ISSUE THREAD

**Issue by timxx** [WisdomShell/codeshell#10]
如下图，会一直输出。正常应该第一段就结束了。。用的是https://huggingface.co/WisdomShell/CodeShell-7B-Chat 跟web_demo.py

![image](https://github.com/WisdomShell/codeshell/assets/1598262/6f9a8b0d-0ecb-4132-b747-d21adf53b7b4)

**Comment by ruixie** [comment]
抱歉，之前的stop_words设置有些问题，代码已更新，请替换之前的模型代码：
