### ISSUE TITLE
CodeShell-Chat模型的prompt template是什么样子的？

### ISSUE THREAD

**Issue by apepkuss** [WisdomShell/codeshell#14]
请问，在使用Chat模型时，多轮对话场景下的prompt template是什么样子的？我们想在[WasmEdge Runtime](https://github.com/WasmEdge/WasmEdge)的ggml-plugin平台下支持CodeShell模型。谢谢！

更新：CodeShell CPP 是基于llama.cpp构建的，那是否能会支持将CodeShell-Chat转换为GGUF格式，运行在llama.cpp上呢？

**Comment by ruixie** [comment]
非常感谢您对CodeShell的支持，Chat模型的template如下：
```
## human: {query}
## assistant: {response}
## human: {query}
## assistant: 
```
代码可以参考模型的build_chat_input方法：
https://github.com/WisdomShell/codeshell/blob/24d8deda3d9cc2ef25264b50709ca9aaf9adf794/model/modeling_codeshell.py#L934

另外，CPP版本支持GGUF格式，我们在llama.cpp的基础上添加了对CodeShell架构的支持。

**Comment by apepkuss** [comment]
@ruixie 非常感谢回复。我看了一下CodeShell CPP，如你提供的信息，在llama.cpp中提供了CodeShell的支持。我尝试使用其中定义的 `convert-codeshell-hf-to-gguf.py` 和 `gguf.py` 将CodeShell-7B-Chat转换为gguf格式，并且使用编译出来的 `quantize` 对gguf模型进行了量化。很完整的工作，很棒！我想请教一下，你们团队是否有计划将CodeShell CPP中对llama.cpp进行的修改提交PR给llama.cpp？谢谢！

**Comment by ruixie** [comment]
谢谢，向llama.cpp提交PR的工作已经在工作计划中，这次开源后我们发现了模型适配以及llama.cpp原生的一些问题，修复完成后会正式提交。

**Comment by apepkuss** [comment]
Great! 期待可以尽快看到你们的工作出现在llama.cpp中。谢谢！
