### ISSUE TITLE
python demos/web_demo.py 跑不起来

### ISSUE THREAD

**Issue by gao746700783** [WisdomShell/codeshell#15]
运行时出现的异常 
$->   python demos/web_demo.py
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retri
es exceeded with url: /WisdomShell/CodeShell-7B-Chat/resolve/main/tokenizer_conf
ig.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection objec
t at 0x000001B7A90EACA0>, 'Connection to huggingface.co timed out. (connect time
out=10)'))"), '(Request ID: 95367310-1ec0-4a52-be48-7ebaa5d1e312)')' thrown whil
e requesting HEAD https://huggingface.co/WisdomShell/CodeShell-7B-Chat/resolve/m
ain/tokenizer_config.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retri
es exceeded with url: /WisdomShell/CodeShell-7B-Chat/resolve/main/config.json (C
aused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000
001B7A90EAFA0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))
"), '(Request ID: 28432436-379f-4e50-a10c-07ebbdda7451)')' thrown while requesti
ng HEAD https://huggingface.co/WisdomShell/CodeShell-7B-Chat/resolve/main/config
.json
......
 raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, coul
dn't find it in the cached files and it looks like WisdomShell/CodeShell-7B-Chat
 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode
at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

https://huggingface.co 访问不了  不会得用魔法吧

**Comment by ruixie** [comment]
是的，huggingface是目前最大的大模型开源社区，我们的模型也在上面进行维护。为了方便国内开发者使用，我们也正在寻找国内的开源地址，近期会更新。
