### ISSUE TITLE
无法在huggingface上下载模型

### ISSUE THREAD

**Issue by ranhaogong** [WisdomShell/codeshell#18]
如题，要么无法访问，偶尔访问成功也无法下载。
![image](https://github.com/WisdomShell/codeshell/assets/73460206/24ef703d-41ce-48f7-87bb-68e57e4397f9)
![image](https://github.com/WisdomShell/codeshell/assets/73460206/81ebb811-c40e-46cd-9008-97c7d38fde98)

**Comment by ranhaogong** [comment]
问题已解决，可以访问镜像网站：https://hf-mirror.com/models?search=CodeShell

**Comment by faxinwang** [comment]
有人下载下来了吗，0kb/s

**Comment by faxinwang** [comment]
有人下载下来了吗，0kb/s

**Comment by ranhaogong** [comment]
@faxinwang ，

> 问题已解决，可以访问镜像网站：https://hf-mirror.com/models?search=CodeShell

在这里成功下载了
