### ISSUE TITLE
我用的是llama.cpp，感觉生成速度有点慢，是配置的问题吗？

### ISSUE THREAD

**Issue by male110** [WisdomShell/codeshell#29]
我用的是llama.cpp，感觉生成速度有点慢，是配置的问题吗？
服务器是32或64G内存。
一个老式的8G显卡，是我配置太低，还是说软件的配置问题

**Comment by weiye** [comment]
llama.cpp itself doesn't have great support for GPUs. If you have an 8G GPU, you might consider deploying the 4bits model using TGI.
