### ISSUE TITLE
Great works for CodeShell-UCB

### ISSUE THREAD

**Issue by ChiYeungLaw** [WisdomShell/codeshell#3]
This benchmark is great for the code intelligence community. I wonder when the details of this benchmark will be released.

**Comment by ChiYeungLaw** [comment]
I can't wait to play on it. 😆

**Comment by ZZR0** [comment]
Thank you for your interest in the benchmark. While we don't have a precise release date as of yet, if everything goes according to plan, we anticipate being able to release the details of this benchmark within next one to two months. Please continue to monitor the official website for updates, we are working diligently to make the details available as soon as possible.

**Comment by chao-peng** [comment]
@ZZR0 Hi! Is the benchmark released?
