### ISSUE TITLE
项目中未提供requirements.txt

### ISSUE THREAD

**Issue by hksanduo** [WisdomShell/codeshell#5]
项目中未提供requirements.txt，是遗漏了吗？

**Comment by ruixie** [comment]
感谢提醒，已更新。

https://github.com/WisdomShell/codeshell/blob/main/requirements.txt

**Comment by LBJ6666** [comment]
> 感谢提醒，已更新。
> 
> https://github.com/WisdomShell/codeshell/blob/main/requirements.txt

@ruixie ，请问下bitsandbytes的版本？
在bitsandbytes=0.43.2和0.43版本，使用CodeShell-7B-Chat-int4 generate 提示如下错误：
AttributeError: 'list' object has no attribute 'absmax'
#71
