### ISSUE TITLE
使用web demo的过程中回答完全牛头不对马嘴

### ISSUE THREAD

**Issue by jungyin** [WisdomShell/codeshell#54]
rt，我尝试直接运训web demo 但在提问时，它给我的答案完全不符合预期，请问是我疏漏了什么重要步骤吗？
![image](https://github.com/WisdomShell/codeshell/assets/44625891/9b990f27-f3d4-4ca1-ac41-88b70dd4b329)
![image](https://github.com/WisdomShell/codeshell/assets/44625891/b62b15b0-abcf-467c-8f9d-af73ee9d2df0)

**Comment by ruixie** [comment]
你好，从截图来看这个回答不像是CodeShell的返回模式，我们尝试复现也没有复现成功，请详细描述你的执行过程并截图，以便我们进一步排查

**Comment by jungyin** [comment]
> 你好，从截图来看这个回答不像是CodeShell的返回模式，我们尝试复现也没有复现成功，请详细描述你的执行过程并截图，以便我们进一步排查

我直接将https://wisemodel.cn/models/WisdomShell/CodeShell-7B-Chat这个地址下的模型，。代码clone下来，直接运行web_demo，在web_demo中发起提问，就返回我这些东西了

**Comment by LuMelon** [comment]
请问这个问题解决了吗？我这边也是一样的现象。

**Comment by jungyin** [comment]
> 请问这个问题解决了吗？我这边也是一样的现象。

还没有，我仍然正在寻找解决方案

**Comment by LuMelon** [comment]
会不会是模型参数文件不对？不知能否建立一个相关的技术交流群。

**Comment by LuMelon** [comment]
确认了是模型参数文件不对，只有.safetensors 中的模型参数文件是对的
