### ISSUE TITLE
请问按照run_finetune.sh微调之后模型还有记忆功能吗

### ISSUE THREAD

**Issue by huknn** [WisdomShell/codeshell#66]
1、CodeShell支持绝大部分主流编程语言，其中包括C#
2、CodeShell提供的模型代码为标准的transformers格式，可以通过transformers架构轻松使用DeepSpeed、Lora等方法，具体可以参考我们给出的微调示例：

https://github.com/WisdomShell/codeshell/blob/6ab83d569d2852d3873682025dfd7e3c758f5b2a/finetune/run_finetune.sh#L19

_Originally posted by @ruixie in https://github.com/WisdomShell/codeshell/issues/21#issuecomment-1773694297_

**Comment by ruixie** [comment]
根据我们的经验，模型微调后的能力和微调语料的质量有很大的关系，确实有微调后灾难性遗忘现象的发生，所以对于微调语料需要精心准备。
