### ISSUE TITLE
在Android Studio安装Codeshell报错，插件无法展示侧边窗口

### ISSUE THREAD

**Issue by Evermaple** [WisdomShell/codeshell#69]
Android Studio Hedgehog | 2023.1.1 Patch 报错如图，安装版本为0.0.3
![image](https://github.com/WisdomShell/codeshell/assets/13623464/57df1430-144e-4076-ac5b-7bdae15ed159)

**Comment by ruixie** [comment]
很抱歉，我们暂时不支持Android Studio 。
