### ISSUE TITLE
有开发xcode插件的计划吗

### ISSUE THREAD

**Issue by tq0426w** [WisdomShell/codeshell#72]
你好，有开发Xcode插件的计划吗？我们看到这个编程助手很好用，目前服务端和Android客户端均可以使用idea插件，但是iOS客户端使用Xcode时没有相应的插件，请问有相应的开发计划吗？非常感谢！

**Comment by ruixie** [comment]
你好，Xcode在我们的计划列表中，但是我们现在主要精力还在模型的优化，Xcode的开发会在后面进行，敬请期待。
